# Hosts a static page
services:
  web:
    build: .
    restart: unless-stopped
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.${URL_PREFIX}loot-table-modifier.rule=Host(`${URL_PREFIX}loot-table-modifier.docs.offsetmonkey538.top`)"
      - "traefik.http.routers.${URL_PREFIX}loot-table-modifier.service=${URL_PREFIX}loot-table-modifier"
      - "traefik.http.services.${URL_PREFIX}loot-table-modifier.loadbalancer.server.port=80"

networks:
  traefik-proxy:
    external: true