# Hosts a static page
services:
  web:
    build: .
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - traefik-proxy
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.${URL_PREFIX}example-site.rule=Host(`${URL_PREFIX}loot-table-modifier.docs.offsetmonkey538.top`)"
      - "traefik.http.routers.${URL_PREFIX}example-site.service=${URL_PREFIX}example-site"
      - "traefik.http.services.${URL_PREFIX}example-site.loadbalancer.server.port=80"

networks:
  traefik-proxy:
    external: true