name: Build artifacts

on:
  push:
    branches:
      - "*"


jobs:
  build-mod:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Generate resources with Gradle
        run: ./gradlew runDatagenClient
        env:
          DISABLE_PROPERTIES_UPDATE: true


      - name: Build with Gradle
        run: ./gradlew build
        env:
          DISABLE_PROPERTIES_UPDATE: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/

  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: danielr1996/envsubst-action@1.1.0
        env:
          URL_PREFIX: staging-
        with:
          input: docs/docker-compose-template.yml
          output: docs/docker-compose.yml

      - run: |
          tar -czf archive.tar.gz docs Dockerfile docker-compose.yml && curl -i -X POST -H "Authorization: Bearer $SEELF_TOKEN" -F environment=$SEELF_ENVIRONMENT -F archive=@archive.tar.gz $SEELF_APPLICATION_URL
        env:
          SEELF_TOKEN: ${{ secrets.SEELF_TOKEN }}
          SEELF_ENVIRONMENT: staging
          SEELF_APPLICATION_URL: https://seelf.oracle.offsetmonkey538.top/api/v1/apps/300qBnG3t1dOFrUGfw1EeWYwKYA/deployments
